# Development stage
FROM node:20 as development
WORKDIR /usr/src/app
COPY . .
RUN npm install
CMD [ "npm", "run", "start" ]

# Builder stage
FROM development as builder
WORKDIR /usr/src/app

# Production stage
FROM alpine:latest as production
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./
RUN npm ci --only=production
CMD [ "npm", "run", "start" ]
